-- One-time backfill of the pre-admin-panel static catalogue into the
-- products table (migration 0005), generated by
-- scripts/generate-backfill-sql.mjs from data/perfumes.csv and
-- data/atelier-supply.csv. Apply after 0005. Idempotent: re-running is
-- safe, existing slugs are left untouched.
--
-- Legacy rows have no perfume_type / product_type_id / mood set (those
-- CSVs never carried that data) -- an admin should fill them in via
-- the edit form when convenient; the public site already tolerates a
-- null Type gracefully (falls back to "Perfume Oil" / "Fragrance
-- Material" display text).

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'belle-eternelle', 'Belle Eternelle', 'A timeless floral built to become an everyday signature, soft petals warmed by a hint of musk.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Feminine')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Rose', 'Powdery Musk', 'Vanilla']) as t(tag)
where p.slug = 'belle-eternelle'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'fleur-de-lumiere', 'Fleur de Lumière', 'A luminous floral that opens like morning light through a Parisian window, delicate and radiant.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Feminine')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['White Flowers', 'Citrus', 'Soft Musk']) as t(tag)
where p.slug = 'fleur-de-lumiere'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'ambre-sauvage', 'Ambre Sauvage', 'A sunlit amber wrapped in warm resin and sandalwood, for evenings that ask to be remembered.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Warm')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Amber', 'Sandalwood', 'Vanilla']) as t(tag)
where p.slug = 'ambre-sauvage'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'bois-sacre', 'Bois Sacré', 'A grounded blend of cedar and incense, quiet and quietly commanding.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Elegant')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Cedarwood', 'Incense', 'Musk']) as t(tag)
where p.slug = 'bois-sacre'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'visionnaire', 'Visionnaire', 'An audacious, forward-looking composition for the woman who sets the trend rather than follows it.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Alluring')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Saffron', 'Amber', 'Leather']) as t(tag)
where p.slug = 'visionnaire'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'mystere-xiii', 'Mystère XIII', 'An enigmatic blend of dark spice and velvet musk, made to intrigue.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Mysterious')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Black Pepper', 'Musk', 'Dark Woods']) as t(tag)
where p.slug = 'mystere-xiii'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'rose-de-minuit', 'Rose de Minuit', 'A rose reimagined after dark, deep petals folded into smoky woods.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Mysterious')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Rose', 'Smoky Woods', 'Amber']) as t(tag)
where p.slug = 'rose-de-minuit'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'cerise-noir', 'Cerise Noir', 'A sultry cherry note laced with dark chocolate and musk.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Alluring')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Cherry', 'Dark Chocolate', 'Musk']) as t(tag)
where p.slug = 'cerise-noir'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'noir-elixir', 'Noir Élixir', 'An intense elixir of black woods and spice, for the boldest hours of the night.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Mysterious')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Black Pepper', 'Oud', 'Amber']) as t(tag)
where p.slug = 'noir-elixir'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'donna-velours', 'Donna Velours', 'A velvet-soft musk draped in powdery iris, made for quiet elegance.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Elegant')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Iris', 'Musk', 'Vanilla']) as t(tag)
where p.slug = 'donna-velours'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'rosalie-elegance', 'Rosalie Élégance', 'A classic rose bouquet finished with silken powder, refined in the truest Parisian sense.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Elegant')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Rose', 'Powder', 'White Musk']) as t(tag)
where p.slug = 'rosalie-elegance'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'paris-nocturne', 'Paris Nocturne', 'A love letter to Paris after midnight, citrus light fading into warm amber streets.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Warm')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Bergamot', 'Amber', 'Musk']) as t(tag)
where p.slug = 'paris-nocturne'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'rouge-royale', 'Rouge Royale', 'An opulent, red-hued fragrance of spice and rose, worn like a crown.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Alluring')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Rose', 'Spice', 'Amber']) as t(tag)
where p.slug = 'rouge-royale'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, mood)
values ('aurielle_collection', 'satin-mystique', 'Satin Mystique', 'A satin-smooth musk with a whisper of vanilla, sensual and understated.', 199, '₱', '10ml / 0.34 fl oz', 'active', 'Alluring')
on conflict (slug) do nothing;
insert into product_tags (product_id, tag)
select p.id, t.tag from products p, unnest(array['Musk', 'Vanilla', 'Soft Woods']) as t(tag)
where p.slug = 'satin-mystique'
on conflict (product_id, tag) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'fast-break-fragrance-001', 'Fast break fragrance', null, 71.22, 'USD', 'KG', 'active', 1)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'wild-bluebell-fragrance-002', 'Wild Bluebell Fragrance', null, 72.12, 'USD', 'KG', 'active', 2)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'eye-candy-fragrance-004', 'eye candy fragrance', null, 72.12, 'USD', 'KG', 'active', 4)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'perfume-gardenia-fragrance-005', 'Perfume Gardenia fragrance', null, 72.12, 'USD', 'KG', 'active', 5)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pure-play-fragrance-006', 'Pure play fragrance', null, 72.12, 'USD', 'KG', 'active', 6)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sandalwood-fragrance-008', 'sandalwood fragrance', null, 75.16, 'USD', 'KG', 'active', 8)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'charming-fragrance-009', 'Charming fragrance', null, 75.16, 'USD', 'KG', 'active', 9)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'baisen-fragrance-010', 'BAISEN Fragrance', null, 75.46, 'USD', 'KG', 'active', 10)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sure-blue-011', 'Sure Blue', null, 76.66, 'USD', 'KG', 'active', 11)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'so-in-love-fragrance-015', 'so in love fragrance', null, 78.78, 'USD', 'KG', 'active', 15)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pure-play-fragrance-016', 'Pure play fragrance', null, 78.78, 'USD', 'KG', 'active', 16)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'love-fragrance-017', 'Love Fragrance', null, 79.7, 'USD', 'KG', 'active', 17)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cologne-fragrance-019', 'Cologne fragrance', null, 82.72, 'USD', 'KG', 'active', 19)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bubble-pop-fragrance-020', 'bubble pop fragrance', null, 83.34, 'USD', 'KG', 'active', 20)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'green-tea-fragrance-021', 'Green Tea Fragrance', null, 84.84, 'USD', 'KG', 'active', 21)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'ice-age-fragrance-023', 'Ice Age fragrance', null, 88.48, 'USD', 'KG', 'active', 23)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lightning-fragrance-024', 'Lightning fragrance', null, 88.78, 'USD', 'KG', 'active', 24)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'happy-hour-fragrance-025', 'happy hour fragrance', null, 88.78, 'USD', 'KG', 'active', 25)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lazy-afternoon-fragrance-026', 'lazy afternoon fragrance', null, 89.4, 'USD', 'KG', 'active', 26)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'miracle-fragrance-028', 'Miracle fragrance', null, 90.3, 'USD', 'KG', 'active', 28)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'perfume-fragrance-031', 'Perfume fragrance', null, 90.9, 'USD', 'KG', 'active', 31)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'woody-fragrance-032', 'Woody fragrance', null, 93.94, 'USD', 'KG', 'active', 32)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'encounter-perfume-fragrance-033', 'Encounter Perfume fragrance', null, 96.36, 'USD', 'KG', 'active', 33)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bench-bum-fragrance-034', 'bench bum fragrance', null, 96.36, 'USD', 'KG', 'active', 34)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'perfume-fragrance-037', 'Perfume Fragrance', null, 106.06, 'USD', 'KG', 'active', 37)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'miracle-fragrance-038', 'Miracle fragrance', null, 106.06, 'USD', 'KG', 'active', 38)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cold-water-fragrance-039', 'Cold water fragrance', null, 106.06, 'USD', 'KG', 'active', 39)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'perfume-green-fragrance-042', 'Perfume (green) fragrance', null, 111.82, 'USD', 'KG', 'active', 42)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lightning-fragrance-043', 'Lightning fragrance', null, 111.82, 'USD', 'KG', 'active', 43)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'eternal-fragrance-046', 'Eternal fragrance', null, 124.24, 'USD', 'KG', 'active', 46)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'charming-fragrance-049', 'Charming fragrance', null, 126.06, 'USD', 'KG', 'active', 49)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bright-perfume-fragrance-050', 'Bright perfume fragrance', null, 128.48, 'USD', 'KG', 'active', 50)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'style-perfume-fragrance-054', 'Style perfume fragrance', null, 154.54, 'USD', 'KG', 'active', 54)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lightning-fragrance-057', 'Lightning fragrance', null, 171.22, 'USD', 'KG', 'active', 57)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'crystal-perfume-fragrance-060', 'Crystal perfume fragrance', null, 302.72, 'USD', 'KG', 'active', 60)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'liushen-fragrance-061', 'Liushen Fragrance', null, 33.04, 'USD', 'KG', 'active', 61)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'red-perfume-fragrance-071', 'Red perfume fragrance', null, 66.06, 'USD', 'KG', 'active', 71)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'purple-perfume-fragrance-072', 'Purple perfume fragrance', null, 60.3, 'USD', 'KG', 'active', 72)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'blue-perfume-fragrance-073', 'Blue perfume fragrance', null, 59.1, 'USD', 'KG', 'active', 73)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'my-sassy-girl-fragrance-074', 'My sassy girl fragrance', null, 94.84, 'USD', 'KG', 'active', 74)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'joy-perfume-fragrance-075', 'Joy perfume fragrance', null, 130.9, 'USD', 'KG', 'active', 75)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dune-perfume-fragrance-077', 'Dune perfume fragrance', null, 141.22, 'USD', 'KG', 'active', 77)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'blue-perfume-fragrance-079', 'Blue perfume fragrance', null, 59.1, 'USD', 'KG', 'active', 79)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'purple-perfume-fragrance-080', 'Purple perfume fragrance', null, 60.3, 'USD', 'KG', 'active', 80)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'wishing-genie-fragrance-081', 'Wishing Genie fragrance', null, 95.76, 'USD', 'KG', 'active', 81)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'coconut-fragrance-082', 'Coconut fragrance', null, 47.28, 'USD', 'KG', 'active', 82)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'choco-moon-fragrance-083', 'Choco moon fragrance', null, 30, 'USD', 'KG', 'active', 83)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mousuf-brown-fragrance-084', 'Mousuf Brown fragrance', null, 147.88, 'USD', 'KG', 'active', 84)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mousuf-pink-fragrance-086', 'Mousuf pink fragrance', null, 138.18, 'USD', 'KG', 'active', 86)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'my-true-style-fragrance-087', 'My True Style fragrance', null, 59.1, 'USD', 'KG', 'active', 87)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mousuf-pink-fragrance-088', 'Mousuf pink fragrance', null, 141.82, 'USD', 'KG', 'active', 88)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'official-club-intense-fragrance-089', 'Official club intense fragrance', null, 178.48, 'USD', 'KG', 'active', 89)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'weekend-pink-fragrance-090', 'Weekend Pink fragrance', null, 94.84, 'USD', 'KG', 'active', 90)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sports-men-fragrance-094', 'Sports (men) fragrance', null, 71.22, 'USD', 'KG', 'active', 94)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'chilled-perfume-for-men-fragrance-095', 'Chilled perfume for men fragrance', null, 49.4, 'USD', 'KG', 'active', 95)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'hot-girl-fragrance-097', 'HOT GIRL fragrance', null, 36.06, 'USD', 'KG', 'active', 97)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'perfume-for-women-fragrance-098', 'Perfume for women fragrance', null, 67.58, 'USD', 'KG', 'active', 98)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'passionate-fragrance-100', 'Passionate fragrance', null, 59.4, 'USD', 'KG', 'active', 100)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'coco-aroma-wood-coco-fragrance-101', 'coco Aroma wood coco fragrance', null, 90.3, 'USD', 'KG', 'active', 101)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pink-lady-fragrance-102', 'Pink Lady fragrance', null, 232.12, 'USD', 'KG', 'active', 102)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'waltz-fragrance-103', 'Waltz fragrance', null, 51.52, 'USD', 'KG', 'active', 103)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'marigold-fragrance-104', 'Marigold fragrance', null, 40.9, 'USD', 'KG', 'active', 104)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cactus-fragrance-105', 'Cactus fragrance', null, 36.36, 'USD', 'KG', 'active', 105)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'love-only-one-fragrance-106', 'Love only One fragrance', null, 63.04, 'USD', 'KG', 'active', 106)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'city-without-darkness-fragrance-107', 'City without darkness fragrance', null, 41.82, 'USD', 'KG', 'active', 107)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'classic-male-fragrance-108', 'Classic male fragrance', null, 71.22, 'USD', 'KG', 'active', 108)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sweet-heart-fragrance-109', 'Sweet heart fragrance', null, 48.18, 'USD', 'KG', 'active', 109)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'club-man-fragrance-113', 'Club man fragrance', null, 181.52, 'USD', 'KG', 'active', 113)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'waltz-fragrance-119', 'Waltz fragrance', null, 81.82, 'USD', 'KG', 'active', 119)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'red-adsaaf-120', 'Red adsaaf', null, 72.12, 'USD', 'KG', 'active', 120)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-yara-121', 'white YARA', null, 145.46, 'USD', 'KG', 'active', 121)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pink-arabia-fragrance-122', 'Pink Arabia Fragrance', null, 130, 'USD', 'KG', 'active', 122)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'saudi-arabia-fragrance-123', 'Saudi Arabia Fragrance', null, 275.16, 'USD', 'KG', 'active', 123)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mysterious-east-fragrance-127', 'Mysterious East fragrance', null, 181.22, 'USD', 'KG', 'active', 127)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'arabic-perfume-fragrance-128', 'Arabic perfume fragrance', null, 126.66, 'USD', 'KG', 'active', 128)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'scent-library-l-b-k-water-131', 'Scent Library L.B.K Water', null, 211.82, 'USD', 'KG', 'active', 131)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-roses-and-magnolias-133', 'White Roses and Magnolias', null, 101.82, 'USD', 'KG', 'active', 133)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'first-ripening-of-jasmine-134', 'First ripening of jasmine', null, 307.88, 'USD', 'KG', 'active', 134)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-shirts-135', 'White Shirts', null, 160.6, 'USD', 'KG', 'active', 135)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sweetheart-rose-136', 'Sweetheart Rose', null, 54.54, 'USD', 'KG', 'active', 136)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'juliette-has-a-gun-fragrance-137', 'Juliette Has A Gun Fragrance', null, 54.54, 'USD', 'KG', 'active', 137)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cosmic-speculation-echo-der-rose-138', 'Cosmic Speculation Echo der Rose', null, 302.42, 'USD', 'KG', 'active', 138)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sun-comforter-139', 'Sun comforter', null, 218.18, 'USD', 'KG', 'active', 139)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'national-creme-candy-140', 'National creme candy', null, 103.64, 'USD', 'KG', 'active', 140)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'ancient-temple-sandalwood-141', 'Ancient temple sandalwood', null, 88.48, 'USD', 'KG', 'active', 141)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'spring-rose-wood-142', 'Spring rose wood', null, 219.7, 'USD', 'KG', 'active', 142)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'atlantic-143', 'Atlantic', null, 70.3, 'USD', 'KG', 'active', 143)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'orange-bubble-144', 'Orange bubble', null, 45.46, 'USD', 'KG', 'active', 144)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'eftinaan-145', 'Eftinaan', null, 133.04, 'USD', 'KG', 'active', 145)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'butterfly-agarwood-benzoin-151', 'Butterfly Agarwood & Benzoin', null, 141.82, 'USD', 'KG', 'active', 151)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'english-pear-freesia-154', 'English Pear & Freesia', null, 59.1, 'USD', 'KG', 'active', 154)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'miss-saigon-sensual-blue-155', 'Miss Saigon - Sensual Blue', null, 53.04, 'USD', 'KG', 'active', 155)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'miss-miller-156', 'Miss Miller', null, 258.48, 'USD', 'KG', 'active', 156)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'laurel-rose-158', 'Laurel Rose', null, 104.84, 'USD', 'KG', 'active', 158)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'laurel-rose-159', 'Laurel Rose', null, 74.54, 'USD', 'KG', 'active', 159)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'the-white-blanc-160', 'The white-blanc', null, 84.84, 'USD', 'KG', 'active', 160)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'inflorescence-161', 'inflorescence', null, 89.4, 'USD', 'KG', 'active', 161)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'noshane-oolong-tea-162', 'Noshane Oolong tea', null, 85.46, 'USD', 'KG', 'active', 162)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'clain-163', 'CLAIN', null, 69.1, 'USD', 'KG', 'active', 163)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'the-white-blanc-164', 'The white-blanc', null, 84.84, 'USD', 'KG', 'active', 164)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'rayanch-gelato-165', 'Rayanch gelato', null, 60.3, 'USD', 'KG', 'active', 165)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'flower-bush-166', 'Flower Bush', null, 89.4, 'USD', 'KG', 'active', 166)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pink-note-167', 'Pink Note', null, 70.3, 'USD', 'KG', 'active', 167)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'night-170', 'Night', null, 117.58, 'USD', 'KG', 'active', 170)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'rare-171', 'Rare', null, 69.7, 'USD', 'KG', 'active', 171)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'elegant-172', 'Elegant', null, 378.18, 'USD', 'KG', 'active', 172)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lime-ramblings-175', 'Lime Ramblings', null, 71.52, 'USD', 'KG', 'active', 175)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'orange-light-eclipses-the-moon-176', 'Orange Light Eclipses the Moon', null, 86.66, 'USD', 'KG', 'active', 176)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'the-realm-of-clarity-177', 'The Realm of Clarity', null, 89.4, 'USD', 'KG', 'active', 177)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'tea-flower-story-178', 'Tea Flower Story', null, 237.88, 'USD', 'KG', 'active', 178)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'love-letter-of-green-mango-179', 'Love Letter of Green Mango', null, 84.24, 'USD', 'KG', 'active', 179)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'crimson-forest-180', 'Crimson Forest', null, 44.24, 'USD', 'KG', 'active', 180)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'rare-183', 'Rare', null, 119.7, 'USD', 'KG', 'active', 183)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bed-184', 'Bed', null, 252.42, 'USD', 'KG', 'active', 184)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'odette-185', 'Odette', null, 172.12, 'USD', 'KG', 'active', 185)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'alda-187', 'Alda', null, 138.18, 'USD', 'KG', 'active', 187)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'alexandria-188', 'Alexandria', null, 480.6, 'USD', 'KG', 'active', 188)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'patchouli-wyatt-189', 'Patchouli Wyatt', null, 108.48, 'USD', 'KG', 'active', 189)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'ylang-ylang-white-190', 'Ylang Ylang White', null, 111.52, 'USD', 'KG', 'active', 190)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'patchouli-ylang-ylang-white-191', 'Patchouli Ylang Ylang White', null, 119.7, 'USD', 'KG', 'active', 191)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'grapefruit-192', 'Grapefruit', null, 180.6, 'USD', 'KG', 'active', 192)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'patchouli-193', 'Patchouli', null, 50.3, 'USD', 'KG', 'active', 193)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sweet-almond-209', 'Sweet Almond', null, 34.84, 'USD', 'KG', 'active', 209)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'deep-blue-poison-210', 'Deep Blue Poison', null, 59.1, 'USD', 'KG', 'active', 210)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'heart-delight-211', 'Heart Delight', null, 74.54, 'USD', 'KG', 'active', 211)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'flower-garden-212', 'Flower Garden', null, 89.4, 'USD', 'KG', 'active', 212)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sage-213', 'Sage', null, 45.46, 'USD', 'KG', 'active', 213)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'eucalyptus-leaf-lavender-214', 'Eucalyptus Leaf Lavender', null, 26.66, 'USD', 'KG', 'active', 214)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'warm-woodsy-scent-215', 'Warm Woodsy Scent', null, 99.4, 'USD', 'KG', 'active', 215)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dogma-217', 'Dogma', null, 122.12, 'USD', 'KG', 'active', 217)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dream-218', 'Dream', null, 94.84, 'USD', 'KG', 'active', 218)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dream-222', 'Dream', null, 60, 'USD', 'KG', 'active', 222)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dogma-223', 'Dogma', null, 60, 'USD', 'KG', 'active', 223)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'french-man-s-perfume-anniversary-edition-225', 'French Man''s Perfume - Anniversary Edition', null, 140.9, 'USD', 'KG', 'active', 225)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'aloe-vera-226', 'Aloe Vera', null, 43.94, 'USD', 'KG', 'active', 226)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dawn-flower-men-s-perfume-228', 'Dawn Flower (Men''s Perfume)', null, 197.58, 'USD', 'KG', 'active', 228)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'honey-melody-229', 'Honey Melody', null, 168.18, 'USD', 'KG', 'active', 229)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mysterious-amber-230', 'Mysterious Amber', null, 175.16, 'USD', 'KG', 'active', 230)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'roman-holiday-231', 'Roman Holiday', null, 77.58, 'USD', 'KG', 'active', 231)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'roman-holiday-232', 'Roman Holiday', null, 43.94, 'USD', 'KG', 'active', 232)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mysterious-amber-233', 'Mysterious Amber', null, 73.64, 'USD', 'KG', 'active', 233)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'honey-melody-234', 'Honey Melody', null, 72.72, 'USD', 'KG', 'active', 234)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dawn-flower-men-s-perfume-235', 'Dawn Flower (Men''s Perfume)', null, 75.16, 'USD', 'KG', 'active', 235)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'office-elite-236', 'Office Elite', null, 241.22, 'USD', 'KG', 'active', 236)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'infinite-possibilities-238', 'Infinite Possibilities', null, 75.16, 'USD', 'KG', 'active', 238)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pure-white-239', 'Pure White', null, 292.72, 'USD', 'KG', 'active', 239)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'office-elite-240', 'Office Elite', null, 72.12, 'USD', 'KG', 'active', 240)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pure-white-242', 'Pure White', null, 75.46, 'USD', 'KG', 'active', 242)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'golden-prestige-243', 'Golden Prestige', null, 81.22, 'USD', 'KG', 'active', 243)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'blue-star-u-246', 'Blue Star U', null, 96.96, 'USD', 'KG', 'active', 246)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'after-the-rain-men-s-fragrance-249', 'After the Rain (Men''s Fragrance)', null, 90.6, 'USD', 'KG', 'active', 249)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'summer-bubbles-254', 'Summer bubbles', null, 97.88, 'USD', 'KG', 'active', 254)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'strolling-through-autumn-colors-255', 'Strolling Through Autumn Colors', null, 41.82, 'USD', 'KG', 'active', 255)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cedar-love-256', 'Cedar Love', null, 40.9, 'USD', 'KG', 'active', 256)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'flower-grass-and-tree-language-257', 'Flower, Grass, and Tree Language', null, 46.06, 'USD', 'KG', 'active', 257)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dreamland-258', 'Dreamland', null, 193.94, 'USD', 'KG', 'active', 258)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'deep-sea-dragon-roar-259', 'Deep Sea Dragon Roar', null, 81.22, 'USD', 'KG', 'active', 259)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pure-wood-260', 'Pure Wood', null, 59.1, 'USD', 'KG', 'active', 260)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'fir-tree-261', 'Fir Tree', null, 58.48, 'USD', 'KG', 'active', 261)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'passionate-palpitations-262', 'Passionate Palpitations', null, 138.78, 'USD', 'KG', 'active', 262)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'ice-and-snow-sandalwood-heart-263', 'Ice and Snow Sandalwood Heart', null, 63.64, 'USD', 'KG', 'active', 263)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dancing-cherry-blossoms-264', 'Dancing Cherry Blossoms', null, 36.96, 'USD', 'KG', 'active', 264)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'northern-wind-265', 'Northern Wind', null, 53.94, 'USD', 'KG', 'active', 265)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'zen-temple-lotus-language-266', 'Zen Temple Lotus Language', null, 89.7, 'USD', 'KG', 'active', 266)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'gardenia-ebony-267', 'Gardenia Ebony', null, 38.78, 'USD', 'KG', 'active', 267)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'forest-ball-268', 'Forest Ball', null, 428.18, 'USD', 'KG', 'active', 268)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'blue-perfume-269', 'Blue Perfume', null, 90.3, 'USD', 'KG', 'active', 269)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'free-and-easy-breeze-270', 'Free and Easy Breeze', null, 109.1, 'USD', 'KG', 'active', 270)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'tidal-amber-271', 'Tidal Amber', null, 34.24, 'USD', 'KG', 'active', 271)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'nobility-272', 'Nobility', null, 36.06, 'USD', 'KG', 'active', 272)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'night-sweetheart-283', 'Night Sweetheart', null, 63.34, 'USD', 'KG', 'active', 283)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'love-of-matcha-284', 'Love of Matcha', null, 120.6, 'USD', 'KG', 'active', 284)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'coconut-lemongrass-285', 'Coconut&Lemongrass', null, 39.4, 'USD', 'KG', 'active', 285)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'watermelon-286', 'Watermelon', null, 41.82, 'USD', 'KG', 'active', 286)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cream-coconut-287', 'Cream&Coconut', null, 37.88, 'USD', 'KG', 'active', 287)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lily-290', 'Lily', null, 55.46, 'USD', 'KG', 'active', 290)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'gardenias-in-bloom-296', 'Gardenias in Bloom', null, 132.72, 'USD', 'KG', 'active', 296)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'laurel-297', 'Laurel', null, 25.76, 'USD', 'KG', 'active', 297)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cold-cotton-298', 'Cold cotton', null, 36.06, 'USD', 'KG', 'active', 298)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'vanilla-fluff-dream-320', 'Vanilla Fluff Dream', null, 127.28, 'USD', 'KG', 'active', 320)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'fruits-party-321', 'Fruits Party', null, 43.94, 'USD', 'KG', 'active', 321)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'romantic-322', 'Romantic', null, 50.9, 'USD', 'KG', 'active', 322)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dreamer-323', 'dreamer', null, 46.06, 'USD', 'KG', 'active', 323)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'relax-324', 'Relax', null, 62.42, 'USD', 'KG', 'active', 324)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'flower-explosion-325', 'Flower Explosion', null, 50, 'USD', 'KG', 'active', 325)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bitter-orange-blossom-347', 'Bitter orange blossom', null, 110.6, 'USD', 'KG', 'active', 347)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'powder-mist-casts-a-shadow-348', 'Powder mist casts a shadow', null, 51.22, 'USD', 'KG', 'active', 348)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'scarlet-witch-349', 'Scarlet Witch', null, 382.72, 'USD', 'KG', 'active', 349)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'call-pretty-350', 'Call Pretty', null, 45.46, 'USD', 'KG', 'active', 350)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'elysion-352', 'Elysion', null, 352.12, 'USD', 'KG', 'active', 352)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'live-an-extravagant-life-353', 'live an extravagant life', null, 520, 'USD', 'KG', 'active', 353)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'baby-powder-359', 'Baby powder', null, 28.78, 'USD', 'KG', 'active', 359)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'dove-fragrance-360', 'Dove fragrance', null, 57.58, 'USD', 'KG', 'active', 360)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'the-different-company-tokyo-bloom-366', 'The Different Company Tokyo Bloom', null, 230.3, 'USD', 'KG', 'active', 366)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'b-elysion-370', 'B Elysion', null, 60.6, 'USD', 'KG', 'active', 370)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'b-live-an-extravagant-life-372', 'B live an extravagant life', null, 60.6, 'USD', 'KG', 'active', 372)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'a-live-an-extravagant-life-375', 'A live an extravagant life', null, 121.22, 'USD', 'KG', 'active', 375)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'a-elysion-376', 'A Elysion', null, 121.22, 'USD', 'KG', 'active', 376)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lutens-la-fille-de-berlin-380', 'Lutens La Fille de Berlin', null, 117.58, 'USD', 'KG', 'active', 380)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'armaf-club-de-nuit-intense-man-389', 'Armaf Club de Nuit Intense Man', null, 536.96, 'USD', 'KG', 'active', 389)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sweet-twilight-394', 'Sweet Twilight', null, 72.72, 'USD', 'KG', 'active', 394)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lutens-la-fille-de-berlin-395', 'Lutens La Fille de Berlin', null, 45.46, 'USD', 'KG', 'active', 395)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'lutens-la-fille-de-berlin-397', 'Lutens La Fille de Berlin', null, 60.6, 'USD', 'KG', 'active', 397)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-mark-399', 'white mark', null, 227.28, 'USD', 'KG', 'active', 399)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'goddess-409', 'goddess', null, 42.42, 'USD', 'KG', 'active', 409)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'goddess-412', 'goddess', null, 60, 'USD', 'KG', 'active', 412)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'classical-sandalwood-413', 'Classical Sandalwood', null, 100, 'USD', 'KG', 'active', 413)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'shallow-sweet-deep-sandalwood-414', 'Shallow Sweet Deep Sandalwood', null, 242.42, 'USD', 'KG', 'active', 414)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'pink-chiffon-424', 'Pink Chiffon', null, 68.18, 'USD', 'KG', 'active', 424)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'mango-425', 'Mango', null, 30.3, 'USD', 'KG', 'active', 425)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'blue-star-u-426', 'Blue Star U', null, 127.28, 'USD', 'KG', 'active', 426)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'golden-prestige-427', 'Golden Prestige', null, 129.7, 'USD', 'KG', 'active', 427)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'saudi-arabia-fragrance-428', 'Saudi Arabia Fragrance', null, 153.94, 'USD', 'KG', 'active', 428)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'saffron-ebony-443', 'Saffron ebony', null, 151.52, 'USD', 'KG', 'active', 443)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'cherry-red-wine-444', 'Cherry Red Wine', null, 151.52, 'USD', 'KG', 'active', 444)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sweet-old-wood-445', 'Sweet old wood', null, 151.52, 'USD', 'KG', 'active', 445)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'leather-saffron-447', 'Leather Saffron', null, 131.22, 'USD', 'KG', 'active', 447)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'vanilla-woods-448', 'Vanilla Woods', null, 113.64, 'USD', 'KG', 'active', 448)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'spice-tobacco-449', 'Spice Tobacco', null, 117.58, 'USD', 'KG', 'active', 449)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-musk-450', 'White Musk', null, 133.04, 'USD', 'KG', 'active', 450)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'rose-oud-451', 'Rose Oud', null, 126.66, 'USD', 'KG', 'active', 451)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'oud-amber-452', 'Oud Amber', null, 137.88, 'USD', 'KG', 'active', 452)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'first-ripening-of-jasmine-458', 'First ripening of jasmine', null, 60.6, 'USD', 'KG', 'active', 458)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'fahrenheit-459', 'Fahrenheit', null, 75.46, 'USD', 'KG', 'active', 459)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'scandal-men-460', 'Scandal men', null, 60, 'USD', 'KG', 'active', 460)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'gissah-one-only-462', 'Gissah-one&only', null, 136.36, 'USD', 'KG', 'active', 462)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'bamboo-474', 'bamboo', null, 36.36, 'USD', 'KG', 'active', 474)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'eventful-dorall-collection-484', 'Eventful Dorall Collection', null, 90.3, 'USD', 'KG', 'active', 484)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-tea-wood-violet-485', 'White Tea&Wood Violet', null, 151.52, 'USD', 'KG', 'active', 485)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'wood-violet-486', 'Wood Violet', null, 151.52, 'USD', 'KG', 'active', 486)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'wood-violet-487', 'Wood Violet', null, 706.06, 'USD', 'KG', 'active', 487)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'sudan-roasted-sandalwood-perfume-488', 'Sudan Roasted Sandalwood perfume', null, 257.58, 'USD', 'KG', 'active', 488)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'fresh-valley-white-orchid-489', 'Fresh Valley White Orchid', null, 98.78, 'USD', 'KG', 'active', 489)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'armaf-club-de-nuit-intense-man-493', 'Armaf Club de Nuit Intense Man', null, 173.34, 'USD', 'KG', 'active', 493)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'white-encounter-500', 'White Encounter', null, 57.58, 'USD', 'KG', 'active', 500)
on conflict (slug) do nothing;

insert into products (category, slug, name, description, price, currency, size, status, serial_number)
values ('atelier_supply', 'soully-valley-white-orchid-504', 'Soully - Valley White Orchid', null, 98.78, 'USD', 'KG', 'active', 504)
on conflict (slug) do nothing;

